### ISSUE TITLE
Shorten link cannot be copied in iPhone

### ISSUE THREAD

**Issue by TeenTin** [SinTan1729/chhoto-url#36]
Shorten link cannot be copied in iPhone even with the latest version 5.4.5.

**Comment by SinTan1729** [comment]
This is known. I didn't add any patched for it yet. I don't use any Apple devices, so I can't test it myself. I'll need someone who know how things work in Safari to help me with it.

**Comment by TeenTin** [comment]
Not only Safari, but all browsers in iPhone are not working, including Chrome.

**Comment by SinTan1729** [comment]
All browsers in iOS use Safari (WebKit, to be exact) as the engine. (It will change soon, but for now it is the situation.) So it's an issue with WebKit.

**Comment by TeenTin** [comment]
I see.  Thanks for your explanation.

**Comment by JZL** [comment]
I'm sorry to say I don't have any iOS/macOS devices to check with either.

I can try to debug when I have time but I've had good luck with e.g. [browserstack](https://www.browserstack.com/) which allows you to open an interactive browser streamed from different devices.

I just tested it with the free plan and it let me boot up an iphone 14 where I could replicate the copy issue. I even learned you can open up devtools on the iphone and get breakpoints + a console, but didn't have time to debug the copying (no error was logged to the console)

**Comment by SinTan1729** [comment]
@JZL Thanks. That seems useful.

**Comment by SinTan1729** [comment]
@TeenTin I tried something. This might be completely useless, so I haven't committed it yet. But can you please test using the `chhoto-url:dev` docker tag to see if it fixes your issue?

**Comment by TeenTin** [comment]
@SinTan1729 Tried.  But I cannot even start the program.

logs:
exec /chhoto-url: exec format error
exec /chhoto-url: exec format error
exec /chhoto-url: exec format error
exec /chhoto-url: exec format error
exec /chhoto-url: exec format error
exec /chhoto-url: exec format error
exec /chhoto-url: exec format error
exec /chhoto-url: exec format error
exec /chhoto-url: exec format error

END OF LINE

**Comment by SinTan1729** [comment]
Are you running it from an x86 device? Dev builds are only built for x86.

**Comment by TeenTin** [comment]
I am running it in docker using Raspberry Pi.

**Comment by SinTan1729** [comment]
Ok. I've set up a temporary test page at https://test.sintan1729.uk with password `pass`. Can you test using that?

**Comment by TeenTin** [comment]
Tested.  Not working.  Same as before.

**Comment by SinTan1729** [comment]
Ok, I'm out of ideas for now. ☹️

**Comment by TeenTin** [comment]
So, as a work around, would you consider adding to show the shortened link so that "long pressing" it can bring up the copy option?

**Comment by SinTan1729** [comment]
Can you try it now? I added a way to detect WebKit and enable the manual copying. The link and password are same.

**Comment by TeenTin** [comment]
The manual copying is working good.

**Comment by TeenTin** [comment]
Adding the newly created shortened link just below or just above the "Shorten!" button would be perfect.

**Comment by SinTan1729** [comment]
This is a stopgap measure, and will be properly fixed in the future. I don't want to make any UI changes.

**Comment by TeenTin** [comment]
@SinTan1729 Tried the new build.  But back to the original problem, still cannot copy manually.

**Comment by SinTan1729** [comment]
This is the same build you tested before. Probably a caching issue. Force refresh the page, or wait a while.

**Comment by TeenTin** [comment]
Seems not due to the cache, because I have created a new shorten link and also refreshed the page.

**Comment by SinTan1729** [comment]
Are you, by any chance, using Cloudflare or some similar proxy service? Those sometimes have a cache that messes things up.

**Comment by TeenTin** [comment]
As far as I know, I have not touched Cloudflare.  I use Dynu ddns for domain name.

Anyway, I find that if I access the page using LAN IP, I can copy the shorten link manually.
![Snap1](https://github.com/user-attachments/assets/4973f1a5-c380-4e58-81f7-b24e1964c417)
e using LAN IP, I can copy the shorten link manually.

**Comment by TeenTin** [comment]
If I access the page with ddns, I get this ...
![Snap1](https://github.com/user-attachments/assets/274fcb0c-d52a-49a3-bbae-3a49ec773f03)

**Comment by SinTan1729** [comment]
I just tested it on an iPhone 15 using BrowserStack, and it does work. Just in case there was some confusion, for non-WebKit browsers, the previous behavior stays i.e. you can click on it and have the link copied. For WebKit based browsers e.g. Safari, it's changed to the shortlink instead of the Javascript, so that you can long click and copy.

**Comment by TeenTin** [comment]
@SinTan1729 
Strange thing happened in my case.  The shorten link has repeated domain name.
![IMG_5894](https://github.com/user-attachments/assets/bb669e0d-44c7-4e36-8e04-f0a4bef98f7d)

**Comment by SinTan1729** [comment]
I'm sorry, I can't reproduce this.

**Comment by SinTan1729** [comment]
Yes, I'm aware of the issue. It's just that I can't reproduce it since I don't use any Apple devices. There needs to be some specialized code to handle this, but I don't have a way to test it. I was looking into emulators, but there are no decent free options.

**Comment by SinTan1729** [comment]
Ok, I guess that might work. Can you please send me login info for the test repo? I'd need that for implementing the fix. Send it to mail@sayantansantra.com via email.

I'll open a PR with potential fixes once I have time. Let's continue our chat there.
